language: java
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8

# We can skip the install step,
# cause everything must be running
# fine without preliminary installation
# into local cache.
install: true
script: "mvn --show-version --errors --batch-mode clean verify"
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - khmarbaise@apache.org
