language: java
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8

# The install step is needed based
# on a problem in maven-invoker-plugin
# https://issues.apache.org/jira/browse/MINVOKER-200
install: 
  - "mvn -DskipTests install"
#
# Run all integration tests.
script: 
  - "mvn -Prun-its --show-version --errors --batch-mode clean verify"
#
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - khmarbaise@apache.org
